# Chapter 55: Sequences, Attention, and Transformers

Inspect transparent attention for a short NRG distributor message.


In [ ]:
from pathlib import Path
import sys,numpy as np,matplotlib.pyplot as plt
sys.path.insert(0,str(Path.cwd().parents[1]/'src'))
from datasciencebook.attention import *
print('Imports ready.')


Imports ready.


In [ ]:
tokens=['stok','kopi','belum','tiba','jakarta']
pos=sinusoidal_positions(len(tokens),6)
print(f'Tokens={len(tokens)}; position shape={pos.shape}')
print('First position:',np.round(pos[0],3).tolist())


Tokens=5; position shape=(5, 6)
First position: [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]


In [ ]:
q=np.array([[1,0],[.8,.2],[0,1],[.2,.8],[.5,.5]],float);v=np.arange(10).reshape(5,2)
out,w=scaled_dot_product_attention(q,q,v)
print('Weight row sums:',np.round(w.sum(axis=1),3).tolist())
print('Highest-attended tokens:',[tokens[i] for i in w.argmax(axis=1)])


Weight row sums: [1.0, 1.0, 1.0, 1.0, 1.0]
Highest-attended tokens: ['stok', 'stok', 'belum', 'belum', 'stok']


In [ ]:
mask=causal_mask(len(tokens));_,causal_w=scaled_dot_product_attention(q,q,v,mask)
print(mask.astype(int))
print(f'Future attention mass={causal_w[np.triu_indices(len(tokens),1)].sum():.1f}')


[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]
Future attention mass=0.0


In [ ]:
fig,axes=plt.subplots(1,2,figsize=(10,4));im=axes[0].imshow(w,cmap='Blues');axes[0].set(xticks=range(5),yticks=range(5),xticklabels=tokens,yticklabels=tokens,title='Self-attention weights');axes[0].tick_params(axis='x',rotation=45);fig.colorbar(im,ax=axes[0],fraction=.046);axes[1].plot(pos);axes[1].set(title='Sinusoidal positions',xlabel='Position',ylabel='Value');fig.tight_layout();plt.show()


## Interpretation

Each row forms a probability distribution over source positions. The causal mask makes all future-position weights exactly zero, while position vectors distinguish token order.


In [ ]:
# Practice: change one query vector and inspect its attention row.
